# Generated by Django 2.2.4 on 2020-04-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semiRestfulApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='network',
            field=models.CharField(max_length=255),
        ),
    ]
