# Generated by Django 2.2.4 on 2020-04-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddyApp', '0002_auto_20200428_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='travler',
        ),
        migrations.AddField(
            model_name='trip',
            name='travler',
            field=models.ManyToManyField(related_name='travel', to='travelBuddyApp.User'),
        ),
    ]
